### ISSUE TITLE
 Cannot find module 'database'

### ISSUE THREAD

**Issue by farell** [Spikef/node-database#1]
运行程序 odbc.js:

var db = require('database');
var config = {dbType: 0, dbPath: './DSCDdata.mdb'};
db.connect(config);             // 返回db自身 

出现下面错误
Error: Cannot find module 'database'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Users\bunny\Desktop\AcquireData\odbc.js:1:10)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)

全局和当前文件夹下的node_modules都有node-database

**Comment by Spikef** [comment]
这个模块主要是用于ClassicASP的，node下目前只支持sqlite和mysql数据库。

**Comment by farell** [comment]
use var db = require('node-database') instead of var db = require('database')
